---
title: " D104 Heat Wave Days Dataset Codebook"
author: "Joyce Robbins "
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ D104 Heat Wave Days }
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
This codebook is provided to assist in determining how to set up a query to the CDC Wonder API. The best way to become familiar with the API is to use the web interface: https://wonder.cdc.gov.  Also, read the [<code>wonderapi</code> vignette](IntroVignette.html) to learn about the basic sections of CDC Wonder query requests.

**Parameter:**
B_1 	 Group Results By 

**Value(s):**
```
		 D104.V2-level2 	 County 
		 D104.V3 	 Year 
```

**Parameter:**
B_2 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D104.V2-level2 	 County 
		 D104.V3 	 Year 
```

**Parameter:**
M_1 	 Sum 

**Parameter:**
M_11 	 Average 

**Parameter:**
M_12 	 Standard Deviation 

**Parameter:**
M_2 	 Sum 

**Parameter:**
M_21 	 Average 

**Parameter:**
M_22 	 Standard Deviation 

**Parameter:**
M_3 	 Sum 

**Parameter:**
M_31 	 Average 

**Parameter:**
M_32 	 Standard Deviation 

**Parameter:**
M_4 	 Sum 

**Parameter:**
M_41 	 Average 

**Parameter:**
M_42 	 Standard Deviation 

**Parameter:**
O_title 	 Title 

**Parameter:**
V_D104.V2 	 Selected Items 

**Parameter:**
F_D104.V2 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 01 	 + 01  (Alabama)   
		 04 	 + 04  (Arizona)   
		 05 	 + 05  (Arkansas)   
		 06 	 + 06  (California)   
		 08 	 + 08  (Colorado)   
		 09 	 + 09  (Connecticut)   
		 10 	 + 10  (Delaware)   
		 11 	 + 11  (District of Columbia)   
		 12 	 + 12  (Florida)   
		 13 	 + 13  (Georgia)   
		 16 	 + 16  (Idaho)   
		 17 	 + 17  (Illinois)   
		 18 	 + 18  (Indiana)   
		 19 	 + 19  (Iowa)   
		 20 	 + 20  (Kansas)   
		 21 	 + 21  (Kentucky)   
		 22 	 + 22  (Louisiana)   
		 23 	 + 23  (Maine)   
		 24 	 + 24  (Maryland)   
		 25 	 + 25  (Massachusetts)   
		 26 	 + 26  (Michigan)   
		 27 	 + 27  (Minnesota)   
		 28 	 + 28  (Mississippi)   
		 29 	 + 29  (Missouri)   
		 30 	 + 30  (Montana)   
		 31 	 + 31  (Nebraska)   
		 32 	 + 32  (Nevada)   
		 33 	 + 33  (New Hampshire)   
		 34 	 + 34  (New Jersey)   
		 35 	 + 35  (New Mexico)   
		 36 	 + 36  (New York)   
		 37 	 + 37  (North Carolina)   
		 38 	 + 38  (North Dakota)   
		 39 	 + 39  (Ohio)   
		 40 	 + 40  (Oklahoma)   
		 41 	 + 41  (Oregon)   
		 42 	 + 42  (Pennsylvania)   
		 44 	 + 44  (Rhode Island)   
		 45 	 + 45  (South Carolina)   
		 46 	 + 46  (South Dakota)   
		 47 	 + 47  (Tennessee)   
		 48 	 + 48  (Texas)   
		 49 	 + 49  (Utah)   
		 50 	 + 50  (Vermont)   
		 51 	 + 51  (Virginia)   
		 53 	 + 53  (Washington)   
		 54 	 + 54  (West Virginia)   
		 55 	 + 55  (Wisconsin)   
		 56 	 + 56  (Wyoming)   
```

**Parameter:**
V_D104.V3 	 Year 

**Value(s):**
```
		 *All* 	  All Years  
		 1981 	  1981  
		 1982 	  1982  
		 1983 	  1983  
		 1984 	  1984  
		 1985 	  1985  
		 1986 	  1986  
		 1987 	  1987  
		 1988 	  1988  
		 1989 	  1989  
		 1990 	  1990  
		 1991 	  1991  
		 1992 	  1992  
		 1993 	  1993  
		 1994 	  1994  
		 1995 	  1995  
		 1996 	  1996  
		 1997 	  1997  
		 1998 	  1998  
		 1999 	  1999  
		 2000 	  2000  
		 2001 	  2001  
		 2002 	  2002  
		 2003 	  2003  
		 2004 	  2004  
		 2005 	  2005  
		 2006 	  2006  
		 2007 	  2007  
		 2008 	  2008  
		 2009 	  2009  
		 2010 	  2010  
```

**Parameter:**
O_precision 	 Precision 

**Value(s):**
```
		 0 	  0  
		 1 	  1  
		 2 	  2  
		 3 	  3  
		 4 	  4  
		 5 	  5  
		 6 	  6  
		 7 	  7  
		 8 	  8  
		 9 	  9  
```

**Parameter:**
O_timeout 	 Data Access Timeout 

**Value(s):**
```
		 60 	  1  
		 120 	  2  
		 180 	  3  
		 240 	  4  
		 300 	  5  
		 360 	  6  
		 420 	  7  
		 480 	  8  
		 540 	  9  
		 600 	  10  
		 660 	  11  
		 720 	  12  
		 780 	  13  
		 840 	  14  
		 900 	  15  
```

