---
title: " D10 Natality for 1995 - 2002 Dataset Codebook"
author: "Joyce Robbins "
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ D10 Natality for 1995 - 2002 }
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
This codebook is provided to assist in determining how to set up a query to the CDC Wonder API. The best way to become familiar with the API is to use the web interface: https://wonder.cdc.gov.  Also, read the [<code>wonderapi</code> vignette](IntroVignette.html) to learn about the basic sections of CDC Wonder query requests.

**Parameter:**
B_1 	 Group Results By 

**Value(s):**
```
		 D10.V22-level1 	 Census Region 
		 D10.V22-level2 	 Census Division 
		 D10.V37-level1 	 HHS Region 
		 D10.V21-level1 	 State 
		 D10.V21-level2 	 County 
		 D10.V4 	 Mother's Hispanic Origin 
		 D10.V2 	 Mother's Race 
		 D10.V1 	 Age of Mother 
		 D10.V5 	 Mother's Education 
		 D10.V20 	 Year 
		 D10.V3 	 Gender 
		 D10.V6 	 Gestational Age at Birth 
		 D10.V7 	 Plurality or Multiple Birth 
		 D10.V8 	 Month Prenatal Care Began 
		 D10.V9 	 Infant Birth Weight 
		 D10.V11 	 Anemia 
		 D10.V12 	 Cardiac Disease 
		 D10.V16 	 Chronic Hypertension 
		 D10.V14 	 Diabetes 
		 D10.V18 	 Eclampsia 
		 D10.V15 	 Hydramnios / Oligohydramnios 
		 D10.V19 	 Incompetent Cervix 
		 D10.V13 	 Lung Disease 
		 D10.V17 	 Pregnancy-associated Hypertension 
		 D10.V10 	 Tobacco Use 
```

**Parameter:**
B_2 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D10.V22-level1 	 Census Region 
		 D10.V22-level2 	 Census Division 
		 D10.V37-level1 	 HHS Region 
		 D10.V21-level1 	 State 
		 D10.V21-level2 	 County 
		 D10.V4 	 Mother's Hispanic Origin 
		 D10.V2 	 Mother's Race 
		 D10.V1 	 Age of Mother 
		 D10.V5 	 Mother's Education 
		 D10.V20 	 Year 
		 D10.V3 	 Gender 
		 D10.V6 	 Gestational Age at Birth 
		 D10.V7 	 Plurality or Multiple Birth 
		 D10.V8 	 Month Prenatal Care Began 
		 D10.V9 	 Infant Birth Weight 
		 D10.V11 	 Anemia 
		 D10.V12 	 Cardiac Disease 
		 D10.V16 	 Chronic Hypertension 
		 D10.V14 	 Diabetes 
		 D10.V18 	 Eclampsia 
		 D10.V15 	 Hydramnios / Oligohydramnios 
		 D10.V19 	 Incompetent Cervix 
		 D10.V13 	 Lung Disease 
		 D10.V17 	 Pregnancy-associated Hypertension 
		 D10.V10 	 Tobacco Use 
```

**Parameter:**
B_3 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D10.V22-level1 	 Census Region 
		 D10.V22-level2 	 Census Division 
		 D10.V37-level1 	 HHS Region 
		 D10.V21-level1 	 State 
		 D10.V21-level2 	 County 
		 D10.V4 	 Mother's Hispanic Origin 
		 D10.V2 	 Mother's Race 
		 D10.V1 	 Age of Mother 
		 D10.V5 	 Mother's Education 
		 D10.V20 	 Year 
		 D10.V3 	 Gender 
		 D10.V6 	 Gestational Age at Birth 
		 D10.V7 	 Plurality or Multiple Birth 
		 D10.V8 	 Month Prenatal Care Began 
		 D10.V9 	 Infant Birth Weight 
		 D10.V11 	 Anemia 
		 D10.V12 	 Cardiac Disease 
		 D10.V16 	 Chronic Hypertension 
		 D10.V14 	 Diabetes 
		 D10.V18 	 Eclampsia 
		 D10.V15 	 Hydramnios / Oligohydramnios 
		 D10.V19 	 Incompetent Cervix 
		 D10.V13 	 Lung Disease 
		 D10.V17 	 Pregnancy-associated Hypertension 
		 D10.V10 	 Tobacco Use 
```

**Parameter:**
B_4 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D10.V22-level1 	 Census Region 
		 D10.V22-level2 	 Census Division 
		 D10.V37-level1 	 HHS Region 
		 D10.V21-level1 	 State 
		 D10.V21-level2 	 County 
		 D10.V4 	 Mother's Hispanic Origin 
		 D10.V2 	 Mother's Race 
		 D10.V1 	 Age of Mother 
		 D10.V5 	 Mother's Education 
		 D10.V20 	 Year 
		 D10.V3 	 Gender 
		 D10.V6 	 Gestational Age at Birth 
		 D10.V7 	 Plurality or Multiple Birth 
		 D10.V8 	 Month Prenatal Care Began 
		 D10.V9 	 Infant Birth Weight 
		 D10.V11 	 Anemia 
		 D10.V12 	 Cardiac Disease 
		 D10.V16 	 Chronic Hypertension 
		 D10.V14 	 Diabetes 
		 D10.V18 	 Eclampsia 
		 D10.V15 	 Hydramnios / Oligohydramnios 
		 D10.V19 	 Incompetent Cervix 
		 D10.V13 	 Lung Disease 
		 D10.V17 	 Pregnancy-associated Hypertension 
		 D10.V10 	 Tobacco Use 
```

**Parameter:**
B_5 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D10.V22-level1 	 Census Region 
		 D10.V22-level2 	 Census Division 
		 D10.V37-level1 	 HHS Region 
		 D10.V21-level1 	 State 
		 D10.V21-level2 	 County 
		 D10.V4 	 Mother's Hispanic Origin 
		 D10.V2 	 Mother's Race 
		 D10.V1 	 Age of Mother 
		 D10.V5 	 Mother's Education 
		 D10.V20 	 Year 
		 D10.V3 	 Gender 
		 D10.V6 	 Gestational Age at Birth 
		 D10.V7 	 Plurality or Multiple Birth 
		 D10.V8 	 Month Prenatal Care Began 
		 D10.V9 	 Infant Birth Weight 
		 D10.V11 	 Anemia 
		 D10.V12 	 Cardiac Disease 
		 D10.V16 	 Chronic Hypertension 
		 D10.V14 	 Diabetes 
		 D10.V18 	 Eclampsia 
		 D10.V15 	 Hydramnios / Oligohydramnios 
		 D10.V19 	 Incompetent Cervix 
		 D10.V13 	 Lung Disease 
		 D10.V17 	 Pregnancy-associated Hypertension 
		 D10.V10 	 Tobacco Use 
```

**Parameter:**
O_title 	 Title 

**Parameter:**
O_location 
**Values:**	 D10.V21 	 States 

**Parameter:**
O_location 
**Values:**	 D10.V22 	 Census Regions 

**Parameter:**
O_location 
**Values:**	 D10.V37 	 HHS Regions 

**Parameter:**
V_D10.V21 	 Selected Items 

**Parameter:**
F_D10.V21 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 01 	 + 01  (Alabama)   
		 02 	 + 02  (Alaska)   
		 04 	 + 04  (Arizona)   
		 05 	 + 05  (Arkansas)   
		 06 	 + 06  (California)   
		 08 	 + 08  (Colorado)   
		 09 	 + 09  (Connecticut)   
		 10 	 + 10  (Delaware)   
		 11 	 + 11  (District of Columbia)   
		 12 	 + 12  (Florida)   
		 13 	 + 13  (Georgia)   
		 15 	 + 15  (Hawaii)   
		 16 	 + 16  (Idaho)   
		 17 	 + 17  (Illinois)   
		 18 	 + 18  (Indiana)   
		 19 	 + 19  (Iowa)   
		 20 	 + 20  (Kansas)   
		 21 	 + 21  (Kentucky)   
		 22 	 + 22  (Louisiana)   
		 23 	 + 23  (Maine)   
		 24 	 + 24  (Maryland)   
		 25 	 + 25  (Massachusetts)   
		 26 	 + 26  (Michigan)   
		 27 	 + 27  (Minnesota)   
		 28 	 + 28  (Mississippi)   
		 29 	 + 29  (Missouri)   
		 30 	 + 30  (Montana)   
		 31 	 + 31  (Nebraska)   
		 32 	 + 32  (Nevada)   
		 33 	 + 33  (New Hampshire)   
		 34 	 + 34  (New Jersey)   
		 35 	 + 35  (New Mexico)   
		 36 	 + 36  (New York)   
		 37 	 + 37  (North Carolina)   
		 38 	 + 38  (North Dakota)   
		 39 	 + 39  (Ohio)   
		 40 	 + 40  (Oklahoma)   
		 41 	 + 41  (Oregon)   
		 42 	 + 42  (Pennsylvania)   
		 44 	 + 44  (Rhode Island)   
		 45 	 + 45  (South Carolina)   
		 46 	 + 46  (South Dakota)   
		 47 	 + 47  (Tennessee)   
		 48 	 + 48  (Texas)   
		 49 	 + 49  (Utah)   
		 50 	 + 50  (Vermont)   
		 51 	 + 51  (Virginia)   
		 53 	 + 53  (Washington)   
		 54 	 + 54  (West Virginia)   
		 55 	 + 55  (Wisconsin)   
		 56 	 + 56  (Wyoming)   
```

**Parameter:**
V_D10.V22 	 Selected Items 

**Parameter:**
F_D10.V22 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 CENS-R1 	 + CENS-R1  (Census Region 1: Northeast)   
		 CENS-R2 	 + CENS-R2  (Census Region 2: Midwest)   
		 CENS-R3 	 + CENS-R3  (Census Region 3: South)   
		 CENS-R4 	 + CENS-R4  (Census Region 4: West)   
```

**Parameter:**
V_D10.V37 	 Selected Items 

**Parameter:**
F_D10.V37 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 HHS1 	 + HHS1  (HHS Region #1  CT, ME, MA, NH, RI, VT)   
		 HHS2 	 + HHS2  (HHS Region #2  NJ, NY)   
		 HHS3 	 + HHS3  (HHS Region #3  DE, DC, MD, PA, VA, WV)   
		 HHS4 	 + HHS4  (HHS Region #4  AL, FL, GA, KY, MS, NC, SC, TN)   
		 HHS5 	 + HHS5  (HHS Region #5  IL, IN, MI, MN, OH, WI)   
		 HHS6 	 + HHS6  (HHS Region #6  AR, LA, NM, OK, TX)   
		 HHS7 	 + HHS7  (HHS Region #7  IA, KS, MO, NE)   
		 HHS8 	 + HHS8  (HHS Region #8  CO, MT, ND, SD, UT, WY)   
		 HHS9 	 + HHS9  (HHS Region #9  AZ, CA, HI, NV)   
		 HHS10 	 + HHS10  (HHS Region #10  AK, ID, OR, WA)   
```

**Parameter:**
V_D10.V4 	 Mother's Hispanic Origin 

**Value(s):**
```
		 *All* 	  All Origins  
		 2148-5 	  Mexican  
		 2180-8 	  Puerto Rican  
		 2182-4 	  Cuban  
		 4 	  Central or South American  
		 5 	  Other and Unknown Hispanic  
		 6 	  Non-Hispanic White  
		 7 	  Non-Hispanic Black  
		 8 	  Non-Hispanic other races  
		 9 	  Origin unknown or not stated  
```

**Parameter:**
V_D10.V2 	 Mother's Race 

**Value(s):**
```
		 *All* 	  All Races  
		 1002-5 	  American Indian or Alaska Native  
		 2054-5 	  Black or African American  
		 2034-7 	  Chinese  
		 2036-2 	  Filipino  
		 2076-8 	  Hawaiian  
		 2039-6 	  Japanese  
		 2028-9 	  Other Asian   
		 2106-3 	  White  
```

**Parameter:**
V_D10.V1 	 Age of Mother 

**Value(s):**
```
		 *All* 	  All Ages  
		 15 	  Under 15 years  
		 15-19 	  15-19 years  
		 20-24 	  20-24 years  
		 25-29 	  25-29 years  
		 30-34 	  30-34 years  
		 35-39 	  35-39 years  
		 40-44 	  40-44 years  
		 45-49 	  45-49 years  
		 50+ 	  50 years and over  
```

**Parameter:**
V_D10.V5 	 Mother's Education 

**Value(s):**
```
		 *All* 	  All Groups  
		 19176 	  0 -  8 years  
		 19177 	  9 - 11 years  
		 19178 	  12 years  
		 19179 	  13 - 15 years  
		 16+ 	  16 years and over  
		 NR 	  Not stated/Not on certificate  
		 999 	  Excluded  
```

**Parameter:**
V_D10.V20 	 Year 

**Value(s):**
```
		 *All* 	  All Years  
		 1995 	  1995  
		 1996 	  1996  
		 1997 	  1997  
		 1998 	  1998  
		 1999 	  1999  
		 2000 	  2000  
		 2001 	  2001  
		 2002 	  2002  
```

**Parameter:**
V_D10.V3 	 Gender 

**Value(s):**
```
		 *All* 	  All Genders  
		 F 	  Female  
		 M 	  Male  
```

**Parameter:**
V_D10.V6 	 Gestational Age at Birth 

**Value(s):**
```
		 *All* 	  All Gestational Weeks  
		 01 	  Under 20 weeks  
		 02 	  20 - 27 weeks  
		 03 	  28 - 31 weeks  
		 04 	  32 - 35 weeks  
		 05 	  36 weeks  
		 06 	  37 - 39 weeks  
		 07 	  40 weeks  
		 08 	  41 weeks  
		 09 	  42 weeks or more  
		 10 	  Unknown or Not Stated  
```

**Parameter:**
V_D10.V7 	 Plurality or Multiple Birth 

**Value(s):**
```
		 *All* 	  All Pluralities  
		 1 	  Single  
		 2 	  Twin  
		 3 	  Triplet  
		 4 	  Quadruplet  
		 5 	  Quintuplet or higher  
```

**Parameter:**
V_D10.V8 	 Month Prenatal Care Began 

**Value(s):**
```
		 *All* 	  All Months  
		 00 	  No prenatal care  
		 01 	  1st month  
		 02 	  2nd month  
		 03 	  3rd month  
		 04 	  4th month  
		 05 	  5th month  
		 06 	  6th month  
		 07 	  7th month  
		 08 	  8th month  
		 09 	  9th month  
		 10 	  10th month  
		 99 	  Unknown or Not Stated  
		 98 	  Not Reported  
```

**Parameter:**
V_D10.V9 	 Infant Birth Weight 

**Value(s):**
```
		 *All* 	  All Weights  
		 01 	  499 grams or less  
		 02 	  500 - 999 grams  
		 03 	  1000 - 1499 grams  
		 04 	  1500 - 1999 grams  
		 05 	  2000 - 2499 grams  
		 06 	  2500 - 2999 grams  
		 07 	  3000 - 3499 grams  
		 08 	  3500 - 3999 grams  
		 09 	  4000 - 4499 grams  
		 10 	  4500 - 4999 grams  
		 11 	  5000 - 8165 grams  
		 12 	  Unknown or Not Stated  
```

**Parameter:**
V_D10.V11 	 Anemia 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V12 	 Cardiac Disease 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V16 	 Chronic Hypertension 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V14 	 Diabetes 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V18 	 Eclampsia 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V15 	 Hydramnios / Oligohydramnios 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V19 	 Incompetent Cervix 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V13 	 Lung Disease 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V17 	 Pregnancy-associated Hypertension 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D10.V10 	 Tobacco Use 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Unknown or Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
precision 	  

**Parameter:**
O_timeout 	 Data Access Timeout 

**Value(s):**
```
		 60 	  1  
		 120 	  2  
		 180 	  3  
		 240 	  4  
		 300 	  5  
		 360 	  6  
		 420 	  7  
		 480 	  8  
		 540 	  9  
		 600 	  10  
		 660 	  11  
		 720 	  12  
		 780 	  13  
		 840 	  14  
		 900 	  15  
```

