---
title: "Introduction_to_the_data.Rmd"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Introduction
This package makes it easier to use the CDC Wonder API.  It does so by employing hidden default query lists and lookup tables, allowing users to focus only on the variables they're interested in obtaining, and writing queries using variable names rather than numeric codes.

The best way to become familiar with CDC Wonder API options is to use the web interface: [https://wonder.cdc.gov](https://wonder.cdc.gov), as the options available through the API are nearly identical. The greatest difference is that location variables are not available through the API.  

## Understanding the structure of a query  

Queries are composed of parameter name-value pairs. There are different types of parameters.  The most crucial are Group Results By and Measures. The Group Results By parameters serve as keys for grouping the data; the maximum number of Group Results By parameters is five.  By default, the query is set to request a single Group Results By parameter: Year, and request a single measure, the same one that is listed as the default measure on the web interface (i.e. `Births` for [the Births dataset](https://wonder.cdc.gov/controller/datarequest/D76), `Deaths` for the [Detailed Mortality dataset](https://wonder.cdc.gov/controller/datarequest/D76).) Queries may be requested relying only on the default settings:  
```{r}
getData(TRUE, "Births") %>% head()
getData(TRUE, "Detailed Mortality") %>% head()
```


Group By Variables
The de




Next, please read the documentation for the single function of the package {getData}. This vignette focuses on setting up the `querylist` parameter passed to this function. The `querylist`



# Introduction to the CDC Natality data

The CDC natality data is documented in detail on the [CDC website] 
(https://wonder.cdc.gov/wonder/help/natality.html).  As always when working with data you need to pay careful attention to data
definitions.  In particular in the case of this data there are at least three time periods which changed the treatment of 
specific variables.  In this package we will use human readable variable names.   Here is the list of variables.

  Variable                    | Years available | Comments
  ----------------------------|-----------------|---------------------------
  Location                   |                | Mother's place of residence  
  Maternal Hispanic Origin   |                 |  
  Marital Status             |                |  
  Age of Mother              ||  
  Maternal Race              ||  
  Maternal Education         ||  
  Year of birth |  |  
  Sex of child |  |  
  Birth weight |  |  
  Plurality or multiple birth |  |    
  Gestational age at birth   |  |  
  Month |  |  
  Weekday   |  |  
  Month prenatal care began |  |  
  Live birth order  |  |  
  Birthplace  |  |  
  Delivery method   |  |  
  Medical attendant   |  |  
  Hypertension-chronic |  |  
  Hypertension-pregnancy |  |  
  Eclampsia |  |  
  Tobacco use |  |  
  Anemia  |  |  
  Cardiac disease |  |  
  Hydramnios  |  | Hydramnios/Oligohydramnios
  Incompentent Cervix |   |  
  Lung disease   |  |  
  
  The CDC has a structured API and this package will make it more readable and therefor easier to use for beginners.
  
  CDC Term |   Word
  ---------|-----------
   B_    | By
   M_   | Measures
   V_    |  Values
   F_    | Finder
   I_   |  Information
   VM_   | Values for non standard age adjusted rates
   O_     |  Other 
   O_age |  Other Age  
   O_ucd  | Underlying cause of death  
   O_V1_fmode  | V1 is year month field, f refers to finder  
   O_   | 
   
   
   
   
