---
title: " D66 Natality for 2007 - 2015 Dataset Codebook"
author: "Joyce Robbins "
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ D66 Natality for 2007 - 2015 }
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
This codebook is provided to assist in determining how to set up a query to the CDC Wonder API. The best way to become familiar with the API is to use the web interface: https://wonder.cdc.gov.  Also, read the [Introduction to wonderapi](wonderapi.html) to learn about the basic sections of CDC Wonder query requests.

**Parameter:**
B_1 	 Group Results By 

**Value(s):**
```
		 D66.V22-level1 	 Census Region 
		 D66.V22-level2 	 Census Division 
		 D66.V37-level1 	 HHS Region 
		 D66.V21-level1 	 State 
		 D66.V21-level2 	 County 
		 D66.V4 	 Hispanic Origin 
		 D66.V2 	 Race 
		 D66.V27 	 Marital Status 
		 D66.V1 	 Age of Mother 9 
		 D66.V38 	 Age of Mother 10 
		 D66.V39 	 Age of Mother 13 
		 D66.V40 	 Age of Mother Year 
		 D66.V5 	 Education 
		 D66.V20 	 Year 
		 D66.V25 	 Month 
		 D66.V26 	 Weekday 
		 D66.V3 	 Gender 
		 D66.V8 	 Month Prenatal Care Began 
		 D66.V9 	 Birth Weight 12 
		 D66.V35 	 Birth Weight 14 
		 D66.V41 	 Birth Weight 100 gram increments 
		 D66.V7 	 Plurality or Multiple Birth 
		 D66.V28 	 Live Birth Order 
		 D66.V30 	 Birthplace 
		 D66.V31 	 Delivery Method 
		 D66.V29 	 Medical Attendant 
		 D66.V6 	 LMP Gestational Age 10 
		 D66.V23 	 LMP Gestational Age 11 
		 D66.V24 	 LMP Gestational Age Weekly 
		 D66.V32 	 OE Gestational Age 10 
		 D66.V33 	 OE Gestational Age 11 
		 D66.V34 	 OE Gestational Age Weekly 
		 D66.V16 	 Chronic Hypertension 
		 D66.V14 	 Diabetes 
		 D66.V17 	 Pregnancy-associated Hypertension 
		 D66.V18 	 Eclampsia 
		 D66.V10 	 Tobacco Use 
```

**Parameter:**
B_2 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D66.V22-level1 	 Census Region 
		 D66.V22-level2 	 Census Division 
		 D66.V37-level1 	 HHS Region 
		 D66.V21-level1 	 State 
		 D66.V21-level2 	 County 
		 D66.V4 	 Hispanic Origin 
		 D66.V2 	 Race 
		 D66.V27 	 Marital Status 
		 D66.V1 	 Age of Mother 9 
		 D66.V38 	 Age of Mother 10 
		 D66.V39 	 Age of Mother 13 
		 D66.V40 	 Age of Mother Year 
		 D66.V5 	 Education 
		 D66.V20 	 Year 
		 D66.V25 	 Month 
		 D66.V26 	 Weekday 
		 D66.V3 	 Gender 
		 D66.V8 	 Month Prenatal Care Began 
		 D66.V9 	 Birth Weight 12 
		 D66.V35 	 Birth Weight 14 
		 D66.V41 	 Birth Weight 100 gram increments 
		 D66.V7 	 Plurality or Multiple Birth 
		 D66.V28 	 Live Birth Order 
		 D66.V30 	 Birthplace 
		 D66.V31 	 Delivery Method 
		 D66.V29 	 Medical Attendant 
		 D66.V6 	 LMP Gestational Age 10 
		 D66.V23 	 LMP Gestational Age 11 
		 D66.V24 	 LMP Gestational Age Weekly 
		 D66.V32 	 OE Gestational Age 10 
		 D66.V33 	 OE Gestational Age 11 
		 D66.V34 	 OE Gestational Age Weekly 
		 D66.V16 	 Chronic Hypertension 
		 D66.V14 	 Diabetes 
		 D66.V17 	 Pregnancy-associated Hypertension 
		 D66.V18 	 Eclampsia 
		 D66.V10 	 Tobacco Use 
```

**Parameter:**
B_3 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D66.V22-level1 	 Census Region 
		 D66.V22-level2 	 Census Division 
		 D66.V37-level1 	 HHS Region 
		 D66.V21-level1 	 State 
		 D66.V21-level2 	 County 
		 D66.V4 	 Hispanic Origin 
		 D66.V2 	 Race 
		 D66.V27 	 Marital Status 
		 D66.V1 	 Age of Mother 9 
		 D66.V38 	 Age of Mother 10 
		 D66.V39 	 Age of Mother 13 
		 D66.V40 	 Age of Mother Year 
		 D66.V5 	 Education 
		 D66.V20 	 Year 
		 D66.V25 	 Month 
		 D66.V26 	 Weekday 
		 D66.V3 	 Gender 
		 D66.V8 	 Month Prenatal Care Began 
		 D66.V9 	 Birth Weight 12 
		 D66.V35 	 Birth Weight 14 
		 D66.V41 	 Birth Weight 100 gram increments 
		 D66.V7 	 Plurality or Multiple Birth 
		 D66.V28 	 Live Birth Order 
		 D66.V30 	 Birthplace 
		 D66.V31 	 Delivery Method 
		 D66.V29 	 Medical Attendant 
		 D66.V6 	 LMP Gestational Age 10 
		 D66.V23 	 LMP Gestational Age 11 
		 D66.V24 	 LMP Gestational Age Weekly 
		 D66.V32 	 OE Gestational Age 10 
		 D66.V33 	 OE Gestational Age 11 
		 D66.V34 	 OE Gestational Age Weekly 
		 D66.V16 	 Chronic Hypertension 
		 D66.V14 	 Diabetes 
		 D66.V17 	 Pregnancy-associated Hypertension 
		 D66.V18 	 Eclampsia 
		 D66.V10 	 Tobacco Use 
```

**Parameter:**
B_4 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D66.V22-level1 	 Census Region 
		 D66.V22-level2 	 Census Division 
		 D66.V37-level1 	 HHS Region 
		 D66.V21-level1 	 State 
		 D66.V21-level2 	 County 
		 D66.V4 	 Hispanic Origin 
		 D66.V2 	 Race 
		 D66.V27 	 Marital Status 
		 D66.V1 	 Age of Mother 9 
		 D66.V38 	 Age of Mother 10 
		 D66.V39 	 Age of Mother 13 
		 D66.V40 	 Age of Mother Year 
		 D66.V5 	 Education 
		 D66.V20 	 Year 
		 D66.V25 	 Month 
		 D66.V26 	 Weekday 
		 D66.V3 	 Gender 
		 D66.V8 	 Month Prenatal Care Began 
		 D66.V9 	 Birth Weight 12 
		 D66.V35 	 Birth Weight 14 
		 D66.V41 	 Birth Weight 100 gram increments 
		 D66.V7 	 Plurality or Multiple Birth 
		 D66.V28 	 Live Birth Order 
		 D66.V30 	 Birthplace 
		 D66.V31 	 Delivery Method 
		 D66.V29 	 Medical Attendant 
		 D66.V6 	 LMP Gestational Age 10 
		 D66.V23 	 LMP Gestational Age 11 
		 D66.V24 	 LMP Gestational Age Weekly 
		 D66.V32 	 OE Gestational Age 10 
		 D66.V33 	 OE Gestational Age 11 
		 D66.V34 	 OE Gestational Age Weekly 
		 D66.V16 	 Chronic Hypertension 
		 D66.V14 	 Diabetes 
		 D66.V17 	 Pregnancy-associated Hypertension 
		 D66.V18 	 Eclampsia 
		 D66.V10 	 Tobacco Use 
```

**Parameter:**
B_5 	 And By 

**Value(s):**
```
		 *None* 	 None 
		 D66.V22-level1 	 Census Region 
		 D66.V22-level2 	 Census Division 
		 D66.V37-level1 	 HHS Region 
		 D66.V21-level1 	 State 
		 D66.V21-level2 	 County 
		 D66.V4 	 Hispanic Origin 
		 D66.V2 	 Race 
		 D66.V27 	 Marital Status 
		 D66.V1 	 Age of Mother 9 
		 D66.V38 	 Age of Mother 10 
		 D66.V39 	 Age of Mother 13 
		 D66.V40 	 Age of Mother Year 
		 D66.V5 	 Education 
		 D66.V20 	 Year 
		 D66.V25 	 Month 
		 D66.V26 	 Weekday 
		 D66.V3 	 Gender 
		 D66.V8 	 Month Prenatal Care Began 
		 D66.V9 	 Birth Weight 12 
		 D66.V35 	 Birth Weight 14 
		 D66.V41 	 Birth Weight 100 gram increments 
		 D66.V7 	 Plurality or Multiple Birth 
		 D66.V28 	 Live Birth Order 
		 D66.V30 	 Birthplace 
		 D66.V31 	 Delivery Method 
		 D66.V29 	 Medical Attendant 
		 D66.V6 	 LMP Gestational Age 10 
		 D66.V23 	 LMP Gestational Age 11 
		 D66.V24 	 LMP Gestational Age Weekly 
		 D66.V32 	 OE Gestational Age 10 
		 D66.V33 	 OE Gestational Age 11 
		 D66.V34 	 OE Gestational Age Weekly 
		 D66.V16 	 Chronic Hypertension 
		 D66.V14 	 Diabetes 
		 D66.V17 	 Pregnancy-associated Hypertension 
		 D66.V18 	 Eclampsia 
		 D66.V10 	 Tobacco Use 
```

**Parameter:**
M_1 	 Births 

**Parameter:**
M_3 	 Birth Rate (Census Region, Census Division, HHS Region, State, County, Year, Race) 

**Parameter:**
M_5 	 Fertility Rate (Census Region, Census Division, HHS Region, State, County, Year, Age of Mother, Race) 

**Parameter:**
M_11 	 Percent of Total Births 

**Parameter:**
M_60 	 Average Birth Weight 

**Parameter:**
M_61 	 Standard Deviation 

**Parameter:**
M_70 	 Average Age of Mother 

**Parameter:**
M_71 	 Standard Deviation 

**Parameter:**
M_80 	 Average LMP Gestational Age 

**Parameter:**
M_81 	 Standard Deviation 

**Parameter:**
M_90 	 Average OE Gestational Age 

**Parameter:**
M_91 	 Standard Deviation 

**Parameter:**
O_title 	 Title 

**Parameter:**
O_rate_per 	 Calculate Rates Per 

**Value(s):**
```
		 1000 	  1,000  
		 10000 	  10,000  
		 100000 	  100,000  
		 1000000 	  1,000,000  
```

**Parameter:**
O_location 
**Values:**	 D66.V21 	 States 

**Parameter:**
O_location 
**Values:**	 D66.V22 	 Census Regions 

**Parameter:**
O_location 
**Values:**	 D66.V37 	 HHS Regions 

**Parameter:**
V_D66.V21 	 Selected Items 

**Parameter:**
F_D66.V21 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 01 	 + 01  (Alabama)   
		 02 	 + 02  (Alaska)   
		 04 	 + 04  (Arizona)   
		 05 	 + 05  (Arkansas)   
		 06 	 + 06  (California)   
		 08 	 + 08  (Colorado)   
		 09 	 + 09  (Connecticut)   
		 10 	 + 10  (Delaware)   
		 11 	 + 11  (District of Columbia)   
		 12 	 + 12  (Florida)   
		 13 	 + 13  (Georgia)   
		 15 	 + 15  (Hawaii)   
		 16 	 + 16  (Idaho)   
		 17 	 + 17  (Illinois)   
		 18 	 + 18  (Indiana)   
		 19 	 + 19  (Iowa)   
		 20 	 + 20  (Kansas)   
		 21 	 + 21  (Kentucky)   
		 22 	 + 22  (Louisiana)   
		 23 	 + 23  (Maine)   
		 24 	 + 24  (Maryland)   
		 25 	 + 25  (Massachusetts)   
		 26 	 + 26  (Michigan)   
		 27 	 + 27  (Minnesota)   
		 28 	 + 28  (Mississippi)   
		 29 	 + 29  (Missouri)   
		 30 	 + 30  (Montana)   
		 31 	 + 31  (Nebraska)   
		 32 	 + 32  (Nevada)   
		 33 	 + 33  (New Hampshire)   
		 34 	 + 34  (New Jersey)   
		 35 	 + 35  (New Mexico)   
		 36 	 + 36  (New York)   
		 37 	 + 37  (North Carolina)   
		 38 	 + 38  (North Dakota)   
		 39 	 + 39  (Ohio)   
		 40 	 + 40  (Oklahoma)   
		 41 	 + 41  (Oregon)   
		 42 	 + 42  (Pennsylvania)   
		 44 	 + 44  (Rhode Island)   
		 45 	 + 45  (South Carolina)   
		 46 	 + 46  (South Dakota)   
		 47 	 + 47  (Tennessee)   
		 48 	 + 48  (Texas)   
		 49 	 + 49  (Utah)   
		 50 	 + 50  (Vermont)   
		 51 	 + 51  (Virginia)   
		 53 	 + 53  (Washington)   
		 54 	 + 54  (West Virginia)   
		 55 	 + 55  (Wisconsin)   
		 56 	 + 56  (Wyoming)   
```

**Parameter:**
V_D66.V22 	 Selected Items 

**Parameter:**
F_D66.V22 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 CENS-R1 	 + CENS-R1  (Census Region 1: Northeast)   
		 CENS-R2 	 + CENS-R2  (Census Region 2: Midwest)   
		 CENS-R3 	 + CENS-R3  (Census Region 3: South)   
		 CENS-R4 	 + CENS-R4  (Census Region 4: West)   
```

**Parameter:**
V_D66.V37 	 Selected Items 

**Parameter:**
F_D66.V37 	 Selected Items 

**Value(s):**
```
		 *All* 	    *All*  (The United States) 
		 HHS1 	 + HHS1  (HHS Region #1  CT, ME, MA, NH, RI, VT)   
		 HHS2 	 + HHS2  (HHS Region #2  NJ, NY)   
		 HHS3 	 + HHS3  (HHS Region #3  DE, DC, MD, PA, VA, WV)   
		 HHS4 	 + HHS4  (HHS Region #4  AL, FL, GA, KY, MS, NC, SC, TN)   
		 HHS5 	 + HHS5  (HHS Region #5  IL, IN, MI, MN, OH, WI)   
		 HHS6 	 + HHS6  (HHS Region #6  AR, LA, NM, OK, TX)   
		 HHS7 	 + HHS7  (HHS Region #7  IA, KS, MO, NE)   
		 HHS8 	 + HHS8  (HHS Region #8  CO, MT, ND, SD, UT, WY)   
		 HHS9 	 + HHS9  (HHS Region #9  AZ, CA, HI, NV)   
		 HHS10 	 + HHS10  (HHS Region #10  AK, ID, OR, WA)   
```

**Parameter:**
V_D66.V4 	 Hispanic Origin 

**Value(s):**
```
		 *All* 	  All Origins  
		 2148-5 	  Mexican  
		 2180-8 	  Puerto Rican  
		 2182-4 	  Cuban  
		 4 	  Central or South American  
		 5 	  Other and Unknown Hispanic  
		 6 	  Non-Hispanic White  
		 7 	  Non-Hispanic Black  
		 8 	  Non-Hispanic other races  
		 9 	  Origin unknown or not stated  
```

**Parameter:**
V_D66.V2 	 Race 

**Value(s):**
```
		 *All* 	  All Races  
		 1002-5 	  American Indian or Alaska Native  
		 A-PI 	  Asian or Pacific Islander  
		 2054-5 	  Black or African American  
		 2106-3 	  White  
```

**Parameter:**
V_D66.V27 	 Marital Status 

**Value(s):**
```
		 *All* 	  All  
		 1 	  Married  
		 2 	  Unmarried  
		 9 	  Unknown or not Stated  
```

**Parameter:**
O_age 
**Values:**	 D66.V1 	 Age of Mother 9 

**Parameter:**
O_age 
**Values:**	 D66.V38 	 Age of Mother 10 

**Parameter:**
O_age 
**Values:**	 D66.V39 	 Age of Mother 13 

**Parameter:**
O_age 
**Values:**	 D66.V40 	 Age of Mother Year 

**Parameter:**
V_D66.V1 	 Age of Mother 9 

**Value(s):**
```
		 *All* 	  All Ages  
		 15 	  Under 15 years  
		 15-19 	  15-19 years  
		 20-24 	  20-24 years  
		 25-29 	  25-29 years  
		 30-34 	  30-34 years  
		 35-39 	  35-39 years  
		 40-44 	  40-44 years  
		 45-49 	  45-49 years  
		 50+ 	  50 years and over  
```

**Parameter:**
V_D66.V38 	 Age of Mother 10 

**Value(s):**
```
		 *All* 	  All Ages  
		 15- 	  Under 15 years  
		 15-17 	  15 - 17 years  
		 18-19 	  18 - 19 years  
		 20-24 	  20-24 years  
		 25-29 	  25-29 years  
		 30-34 	  30-34 years  
		 35-39 	  35-39 years  
		 40-44 	  40-44 years  
		 45-49 	  45-49 years  
		 50+ 	  50 years and over  
```

**Parameter:**
V_D66.V39 	 Age of Mother 13 

**Value(s):**
```
		 *All* 	  All Ages  
		 15- 	  Under 15 years  
		 15 	  15 years  
		 16 	  16 years  
		 17 	  17 years  
		 18 	  18 years  
		 19 	  19 years  
		 20-24 	  20-24 years  
		 25-29 	  25-29 years  
		 30-34 	  30-34 years  
		 35-39 	  35-39 years  
		 40-44 	  40-44 years  
		 45-49 	  45-49 years  
		 50+ 	  50 years and over  
```

**Parameter:**
V_D66.V40 	 Age of Mother Year 

**Value(s):**
```
		 *All* 	  All Ages  
		 10-12 	  10-12 years  
		 13 	  13 years  
		 14 	  14 years  
		 15 	  15 years  
		 16 	  16 years  
		 17 	  17 years  
		 18 	  18 years  
		 19 	  19 years  
		 20 	  20 years  
		 21 	  21 years  
		 22 	  22 years  
		 23 	  23 years  
		 24 	  24 years  
		 25 	  25 years  
		 26 	  26 years  
		 27 	  27 years  
		 28 	  28 years  
		 29 	  29 years  
		 30 	  30 years  
		 31 	  31 years  
		 32 	  32 years  
		 33 	  33 years  
		 34 	  34 years  
		 35 	  35 years  
		 36 	  36 years  
		 37 	  37 years  
		 38 	  38 years  
		 39 	  39 years  
		 40 	  40 years  
		 41 	  41 years  
		 42 	  42 years  
		 43 	  43 years  
		 44 	  44 years  
		 45 	  45 years  
		 46 	  46 years  
		 47 	  47 years  
		 48 	  48 years  
		 49 	  49 years  
		 50+ 	  50 years and over  
```

**Parameter:**
V_D66.V5 	 Education 

**Value(s):**
```
		 *All* 	  All Groups  
		 1 	  8th grade or less  
		 2 	  9th through 12th grade with no diploma  
		 3 	  High school graduate or GED completed  
		 4 	  Some college credit, but not a degree  
		 5 	  Associate degree (AA, AS)  
		 6 	  Bachelor's degree (BA, AB, BS)  
		 7 	  Master's degree (MA, MS)  
		 8 	  Doctorate (PHD, EdD) or Professional Degree (MD, DDS, DVM, LLB, JD)  
		 Unk 	  Unknown/Not on certificate  
		 999 	  Excluded  
```

**Parameter:**
V_D66.V20 	 Year 

**Value(s):**
```
		 *All* 	  All Years  
		 2007 	  2007  
		 2008 	  2008  
		 2009 	  2009  
		 2010 	  2010  
		 2011 	  2011  
		 2012 	  2012  
		 2013 	  2013  
		 2014 	  2014  
		 2015 	  2015  
```

**Parameter:**
V_D66.V25 	 Month 

**Value(s):**
```
		 *All* 	  All Months  
		 1 	  January  
		 2 	  February  
		 3 	  March  
		 4 	  April  
		 5 	  May  
		 6 	  June  
		 7 	  July  
		 8 	  August  
		 9 	  September  
		 10 	  October  
		 11 	  November  
		 12 	  December  
```

**Parameter:**
V_D66.V26 	 Weekday 

**Value(s):**
```
		 *All* 	  All Days  
		 1 	  Sunday  
		 2 	  Monday  
		 3 	  Tuesday  
		 4 	  Wednesday  
		 5 	  Thursday  
		 6 	  Friday  
		 7 	  Saturday  
		 9 	  Unknown  
```

**Parameter:**
V_D66.V3 	 Gender 

**Value(s):**
```
		 *All* 	  All Genders  
		 F 	  Female  
		 M 	  Male  
```

**Parameter:**
V_D66.V8 	 Month Prenatal Care Began 

**Value(s):**
```
		 *All* 	  All Months  
		 00 	  No prenatal care  
		 01 	  1st month  
		 02 	  2nd month  
		 03 	  3rd month  
		 04 	  4th month  
		 05 	  5th month  
		 06 	  6th month  
		 07 	  7th month  
		 08 	  8th month  
		 09 	  9th month  
		 10 	  10th month  
		 99 	  Not stated/Not on certificate  
		 98 	  Excluded  
```

**Parameter:**
O_weight 
**Values:**	 D66.V9 	 Birth Weight 12 

**Parameter:**
O_weight 
**Values:**	 D66.V35 	 Birth Weight 14 

**Parameter:**
O_weight 
**Values:**	 D66.V41 	 Birth Weight 100 gram increments 

**Parameter:**
V_D66.V9 	 Birth Weight 12 

**Value(s):**
```
		 *All* 	  All Weights  
		 01 	  499 grams or less  
		 02 	  500 - 999 grams  
		 03 	  1000 - 1499 grams  
		 04 	  1500 - 1999 grams  
		 05 	  2000 - 2499 grams  
		 06 	  2500 - 2999 grams  
		 07 	  3000 - 3499 grams  
		 08 	  3500 - 3999 grams  
		 09 	  4000 - 4499 grams  
		 10 	  4500 - 4999 grams  
		 11 	  5000 - 8165 grams  
		 12 	  Not stated  
```

**Parameter:**
V_D66.V35 	 Birth Weight 14 

**Value(s):**
```
		 *All* 	  All Weights  
		 01 	  499 grams or less  
		 02 	  500 - 749 grams  
		 03 	  750 - 999 grams  
		 04 	  1000 - 1249 grams  
		 05 	  1250 - 1499 grams  
		 06 	  1500 - 1999 grams  
		 07 	  2000 - 2499 grams  
		 08 	  2500 - 2999 grams  
		 09 	  3000 - 3499 grams  
		 10 	  3500 - 3999 grams  
		 11 	  4000 - 4499 grams  
		 12 	  4500 - 4999 grams  
		 13 	  5000 - 8165 grams  
		 14 	  Not stated  
```

**Parameter:**
V_D66.V41 	 Birth Weight 100 gram increments 

**Value(s):**
```
		 *All* 	  All Weights  
		 1 	  100 - 199 grams  
		 2 	  200 - 299 grams  
		 3 	  300 - 399 grams  
		 4 	  400 - 499 grams  
		 5 	  500 - 599 grams  
		 6 	  600 - 699 grams  
		 7 	  700 - 799 grams  
		 8 	  800 - 899 grams  
		 9 	  900 - 999 grams  
		 10 	  1000 - 1099 grams  
		 11 	  1100 - 1199 grams  
		 12 	  1200 - 1299 grams  
		 13 	  1300 - 1399 grams  
		 14 	  1400 - 1499 grams  
		 15 	  1500 - 1599 grams  
		 16 	  1600 - 1699 grams  
		 17 	  1700 - 1799 grams  
		 18 	  1800 - 1899 grams  
		 19 	  1900 - 1999 grams  
		 20 	  2000 - 2099 grams  
		 21 	  2100 - 2199 grams  
		 22 	  2200 - 2299 grams  
		 23 	  2300 - 2399 grams  
		 24 	  2400 - 2499 grams  
		 25 	  2500 - 2599 grams  
		 26 	  2600 - 2699 grams  
		 27 	  2700 - 2799 grams  
		 28 	  2800 - 2899 grams  
		 29 	  2900 - 2999 grams  
		 30 	  3000 - 3099 grams  
		 31 	  3100 - 3199 grams  
		 32 	  3200 - 3299 grams  
		 33 	  3300 - 3399 grams  
		 34 	  3400 - 3499 grams  
		 35 	  3500 - 3599 grams  
		 36 	  3600 - 3699 grams  
		 37 	  3700 - 3799 grams  
		 38 	  3800 - 3899 grams  
		 39 	  3900 - 3999 grams  
		 40 	  4000 - 4099 grams  
		 41 	  4100 - 4199 grams  
		 42 	  4200 - 4299 grams  
		 43 	  4300 - 4399 grams  
		 44 	  4400 - 4499 grams  
		 45 	  4500 - 4599 grams  
		 46 	  4600 - 4699 grams  
		 47 	  4700 - 4799 grams  
		 48 	  4800 - 4899 grams  
		 49 	  4900 - 4999 grams  
		 50 	  5000 - 5099 grams  
		 51 	  5100 - 5199 grams  
		 52 	  5200 - 5299 grams  
		 53 	  5300 - 5399 grams  
		 54 	  5400 - 5499 grams  
		 55 	  5500 - 5599 grams  
		 56 	  5600 - 5699 grams  
		 57 	  5700 - 5799 grams  
		 58 	  5800 - 5899 grams  
		 59 	  5900 - 5999 grams  
		 60 	  6000 - 6099 grams  
		 61 	  6100 - 6199 grams  
		 62 	  6200 - 6299 grams  
		 63 	  6300 - 6399 grams  
		 64 	  6400 - 6499 grams  
		 65 	  6500 - 6599 grams  
		 66 	  6600 - 6699 grams  
		 67 	  6700 - 6799 grams  
		 68 	  6800 - 6899 grams  
		 69 	  6900 - 6999 grams  
		 70 	  7000 - 7099 grams  
		 71 	  7100 - 7199 grams  
		 72 	  7200 - 7299 grams  
		 73 	  7300 - 7399 grams  
		 74 	  7400 - 7499 grams  
		 75 	  7500 - 7599 grams  
		 76 	  7600 - 7699 grams  
		 77 	  7700 - 7799 grams  
		 78 	  7800 - 7899 grams  
		 79 	  7900 - 7999 grams  
		 80 	  8000 - 8099 grams  
		 81 	  8100 - 8165 grams  
		 99 	  Not stated  
```

**Parameter:**
V_D66.V28 	 Live Birth Order 

**Value(s):**
```
		 *All* 	  All Orders  
		 01 	  1st child born alive to mother  
		 02 	  2nd child born alive to mother  
		 03 	  3rd child born alive to mother  
		 04 	  4th child born alive to mother  
		 05 	  5th child born alive to mother  
		 06 	  6th child and over born alive to mother  
		 99 	  Unknown or not stated  
```

**Parameter:**
V_D66.V7 	 Plurality or Multiple Birth 

**Value(s):**
```
		 *All* 	  All Pluralities  
		 1 	  Single  
		 2 	  Twin  
		 3 	  Triplet  
		 4 	  Quadruplet  
		 5 	  Quintuplet or higher  
```

**Parameter:**
V_D66.V30 	 Birthplace 

**Value(s):**
```
		 *All* 	  All Locations  
		 1 	  In Hospital  
		 2 	  Freestanding Birth Center  
		 3 	  Clinic/Doctor's Office  
		 4 	  Residence  
		 5 	  Other  
		 9 	  Unknown  
```

**Parameter:**
V_D66.V31 	 Delivery Method 

**Value(s):**
```
		 *All* 	  All Methods  
		 1 	  Vaginal  
		 2 	  Cesarean  
		 9 	  Not Stated  
```

**Parameter:**
V_D66.V29 	 Medical Attendant 

**Value(s):**
```
		 *All* 	  All Attendants  
		 1 	  Doctor of Medicine(MD)  
		 2 	  Doctor of Osteopathy(DO)  
		 3 	  Certified Nurse Midwife(CNM)  
		 4 	  Other Midwife  
		 5 	  Other  
		 9 	  Unknown or not stated  
```

**Parameter:**
O_gestation 
**Values:**	 D66.V6 	 LMP Gestational Age 10 

**Parameter:**
O_gestation 
**Values:**	 D66.V23 	 LMP Gestational Age 11 

**Parameter:**
O_gestation 
**Values:**	 D66.V24 	 LMP Gestational Age Weekly 

**Parameter:**
V_D66.V6 	 LMP Gestational Age 10 

**Value(s):**
```
		 *All* 	  All Weeks  
		 01 	  Under 20 weeks  
		 02 	  20 - 27 weeks  
		 03 	  28 - 31 weeks  
		 04 	  32 - 35 weeks  
		 05 	  36 weeks  
		 06 	  37 - 39 weeks  
		 07 	  40 weeks  
		 08 	  41 weeks  
		 09 	  42 weeks or more  
		 10 	  Unknown  
```

**Parameter:**
V_D66.V23 	 LMP Gestational Age 11 

**Value(s):**
```
		 *All* 	  All Weeks  
		 01 	  Under 20 weeks  
		 02 	  20-27 weeks  
		 03 	  28-31 weeks  
		 04 	  32-33 weeks  
		 05 	  34-36 weeks  
		 06 	  37-38 weeks  
		 07 	  39 weeks  
		 08 	  40 weeks  
		 09 	  41 weeks  
		 10 	  42 or more weeks  
		 11 	  Unknown  
```

**Parameter:**
V_D66.V24 	 LMP Gestational Age Weekly 

**Value(s):**
```
		 *All* 	  All Weeks  
		 17 	  17 weeks  
		 18 	  18 weeks  
		 19 	  19 weeks  
		 20 	  20 weeks  
		 21 	  21 weeks  
		 22 	  22 weeks  
		 23 	  23 weeks  
		 24 	  24 weeks  
		 25 	  25 weeks  
		 26 	  26 weeks  
		 27 	  27 weeks  
		 28 	  28 weeks  
		 29 	  29 weeks  
		 30 	  30 weeks  
		 31 	  31 weeks  
		 32 	  32 weeks  
		 33 	  33 weeks  
		 34 	  34 weeks  
		 35 	  35 weeks  
		 36 	  36 weeks  
		 37 	  37 weeks  
		 38 	  38 weeks  
		 39 	  39 weeks  
		 40 	  40 weeks  
		 41 	  41 weeks  
		 42 	  42 weeks  
		 43 	  43 weeks  
		 44 	  44 weeks  
		 45 	  45 weeks  
		 46 	  46 weeks  
		 47 	  47 weeks  
		 99 	  Unknown  
```

**Parameter:**
O_oe_gestation 
**Values:**	 D66.V32 	 OE Gestational Age 10 

**Parameter:**
O_oe_gestation 
**Values:**	 D66.V33 	 OE Gestational Age 11 

**Parameter:**
O_oe_gestation 
**Values:**	 D66.V34 	 OE Gestational Age Weekly 

**Parameter:**
V_D66.V32 	 OE Gestational Age 10 

**Value(s):**
```
		 *All* 	  All Weeks  
		 01 	  Under 20 weeks  
		 02 	  20 - 27 weeks  
		 03 	  28 - 31 weeks  
		 04 	  32 - 35 weeks  
		 05 	  36 weeks  
		 06 	  37 - 39 weeks  
		 07 	  40 weeks  
		 08 	  41 weeks  
		 09 	  42 weeks or more  
		 10 	  Unknown  
```

**Parameter:**
V_D66.V33 	 OE Gestational Age 11 

**Value(s):**
```
		 *All* 	  All Weeks  
		 01 	  Under 20 weeks  
		 02 	  20-27 weeks  
		 03 	  28-31 weeks  
		 04 	  32-33 weeks  
		 05 	  34-36 weeks  
		 06 	  37-38 weeks  
		 07 	  39 weeks  
		 08 	  40 weeks  
		 09 	  41 weeks  
		 10 	  42 or more weeks  
		 11 	  Unknown  
```

**Parameter:**
V_D66.V34 	 OE Gestational Age Weekly 

**Value(s):**
```
		 *All* 	  All Weeks  
		 17 	  17 weeks  
		 18 	  18 weeks  
		 19 	  19 weeks  
		 20 	  20 weeks  
		 21 	  21 weeks  
		 22 	  22 weeks  
		 23 	  23 weeks  
		 24 	  24 weeks  
		 25 	  25 weeks  
		 26 	  26 weeks  
		 27 	  27 weeks  
		 28 	  28 weeks  
		 29 	  29 weeks  
		 30 	  30 weeks  
		 31 	  31 weeks  
		 32 	  32 weeks  
		 33 	  33 weeks  
		 34 	  34 weeks  
		 35 	  35 weeks  
		 36 	  36 weeks  
		 37 	  37 weeks  
		 38 	  38 weeks  
		 39 	  39 weeks  
		 40 	  40 weeks  
		 41 	  41 weeks  
		 42 	  42 weeks  
		 43 	  43 weeks  
		 44 	  44 weeks  
		 45 	  45 weeks  
		 46 	  46 weeks  
		 47 	  47 weeks  
		 99 	  Unknown  
```

**Parameter:**
V_D66.V16 	 Chronic Hypertension 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D66.V14 	 Diabetes 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D66.V17 	 Pregnancy-associated Hypertension 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D66.V18 	 Eclampsia 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
V_D66.V10 	 Tobacco Use 

**Value(s):**
```
		 *All* 	  All Values  
		 1 	  Yes  
		 2 	  No  
		 9 	  Not Stated  
		 10 	  Not Reported  
```

**Parameter:**
O_precision 	 Precision 

**Value(s):**
```
		 0 	  0  
		 1 	  1  
		 2 	  2  
		 3 	  3  
		 4 	  4  
		 5 	  5  
		 6 	  6  
		 7 	  7  
		 8 	  8  
		 9 	  9  
```

**Parameter:**
O_timeout 	 Data Access Timeout 

**Value(s):**
```
		 60 	  1  
		 120 	  2  
		 180 	  3  
		 240 	  4  
		 300 	  5  
		 360 	  6  
		 420 	  7  
		 480 	  8  
		 540 	  9  
		 600 	  10  
		 660 	  11  
		 720 	  12  
		 780 	  13  
		 840 	  14  
		 900 	  15  
```

